image: node:latest

before_script:
  - npm install

services:
  - mysql:latest

variables:
  MYSQL_USER: myadmin
  MYSQL_PASSWORD: Cs428grh!

stages:
  - dev
  - test

dev:
  stage: dev
  script:
    - concurrently --kill-others-on-fail "npm run server" "npm run client"
    
test:
  stage: test
  script:
    - mocha
