image: node:latest

before_script:
  - npm install

stages:
  - server
  - client
  - test

server:
  stage: server
  script:
    - nodemon server.js

client:
  stage: client
  script:
    - cd client
    - npm start
    
test:
  stage: test
  script:
    - mocha
