image: node:latest

services:
  - mysql:latest

variables:
  MYSQL_USER: myadmin
  MYSQL_PASSWORD: Cs428grh!

stages:
  - client
  - server
  - dev
  - test

client:
  stage: client
  script:
    - npm install
    - cd client && npm start

server:
  stage: server
  script:
    - nodemon server.js

dev:
  stage: dev
  script:
    - concurrently --kill-others-on-fail "npm run server" "npm run client"
    
test:
  stage: test
  script:
    - mocha
