image: node:latest

before_script:
  - npm install
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - npm install chromedriver

stages:
  - test
    
test:
  stage: test
  script:
    - mocha test/selenium
