language: node_js
node_js:
 - "stable"
 
before_script:
  - npm install
  - npm install -g npm-run-all
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - cd client
  - npm install
  - cd ..
  
addons:
  apt:
    packages:
      - google-chrome-stable

script:
  - node server.js &
  - cd client
  - npm start
  - cd ..
  - mocha test/selenium
  - mocha test/backend
