language: node_js
node_js:
 - "stable"
 
sudo: required
 
before_script:
  - npm install
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - cd client
  - npm install
  - cd ..
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - node server.js &
  - sleep 10
  - cd client
  - npm start &
  - sleep 30
  - cd ..
  - mocha test/selenium
  - mocha test/backend
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cd client; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cp -R build ..; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cd ..; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mv build public; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then git add public; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then git checkout -b azure-deploy; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then git commit -m "Deploy to Azure"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then git push --force https://gh428:GH428429@grhfree.scm.azurewebsites.net:443/grhfree.git master; fi