language: node_js
node_js:
 - "stable"
 
sudo: required
 
before_script:
  - npm install
  - npm install -g mocha
  - npm install -g selenium-webdriver
  - cd client
  - npm install
  - cd ..
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - node server.js &
  - sleep 10
  - cd client
  - npm start &
  - sleep 30
  - cd ..
  - mocha test/selenium
  - mocha test/backend
