language: node_js
node_js:
 - "stable"
 
before_script:
  - npm install
  - npm install -g mocha
  - npm install -g selenium-webdriver
  
addons:
  apt:
    packages:
      - google-chrome-stable

script:
  - mocha test/selenium
  - mocha test/backend
